version: '3'

services:
  discord_bot:
    container_name: saboteur
    build: .
    volumes:
      - ./config.test.json:/usr/src/saboteur/config.json
      - ./permission.json:/usr/src/saboteur/permission.json
    restart: always

networks:
  default:
    external:
      name: ng_network
